import React from 'react';
import DataTable from 'components/DataTable';
import Icon from 'components/Icon';
import Button from 'components/Button';

export const columns1 = [
  {
    title: '排名',
    name: 'sort',
    tableItem: {},
    searchItem: {
      group: 'abc'
    },
    formItem: {}
  },
  {
    title: '用户名',
    name: 'name',
    tableItem: {},
    formItem: {},
    searchItem: {}
  },
  {
    title: '昨日用气量',
    name: 'used',
    formItem: {},
    tableItem: {},
  },
  {
    title: '昨日申报量',
    name: 'declare',
    formItem: {},
    tableItem: {},
  }
];

export const columns2 = [
  {
    moment: "00:00",
    todayForecast: 40,
    lastMonth: 45,
    lastWeek: 50,
    yesterday: 30,
    today: 50,
  },
  {
    moment: "01:00",
    todayForecast: 60,
    lastMonth: 45,
    lastWeek: 30,
    yesterday: 20,
    today: 70,
  },
  {
    moment: "02:00",
    todayForecast: 53,
    lastMonth: 45,
    lastWeek: 50,
    yesterday: 30,
    today: 50,
  },
  {
    moment: "03:00",
    todayForecast: 58,
    lastMonth: 45,
    lastWeek: 50,
    yesterday: 40,
    today:44,
  },
  {
    moment: "04:00",
    todayForecast: 62,
    lastMonth: 45,
    lastWeek: 40,
    yesterday: 30,
    today: 50,
  },
  {
    moment: "05:00",
    todayForecast: 65,
    lastMonth: 45,
    lastWeek: 50,
    yesterday: 20,
    today: 44,
  },
  {
    moment: "06:00",
    todayForecast: 41,
    lastMonth: 45,
    lastWeek: 60,
    yesterday: 30,
    today: 50,
  },
  {
    moment: "07:00",
    todayForecast: 42,
    lastMonth: 45,
    lastWeek: 60,
    yesterday: 40,
    today: 44,
  },
  {
    moment: "08:00",
    todayForecast: 45,
    lastMonth: 45,
    lastWeek: 50,
    yesterday: 30,
    today: 50,
  },
  {
    moment: "09:00",
    todayForecast: 70,
    lastMonth: 45,
    lastWeek: 40,
    yesterday: 20,
    today: 44,
  },
  {
    moment: "10:00",
    todayForecast: 39,
    lastMonth: 45,
    lastWeek: 50,
    yesterday: 30,
    today: 50,
  },
  {
    moment: "11:00",
    todayForecast: 51,
    lastMonth: 45,
    lastWeek: 40,
    yesterday: 50,
    today: 44,
  },
  {
    moment: "12:00",
    todayForecast: 54,
    lastMonth: 45,
    lastWeek: 50,
    yesterday: 30,
    today: 50,
  },
  {
    moment: "13:00",
    todayForecast: 41,
    lastMonth: 45,
    lastWeek: 40,
    yesterday: 20,
    today: 44,
  },
  {
    moment: "14:00",
    todayForecast: 50,
    lastMonth: 45,
    lastWeek: 50,
    yesterday: 30,
    today: 50,
  },
  {
    moment: "15:00",
    todayForecast: 42,
    lastMonth: 45,
    lastWeek: 40,
    yesterday: 20,
    today: 44,
  },
  {
    moment: "16:00",
    todayForecast: 34,
    lastMonth: 60,
    lastWeek: 50,
    yesterday: 30,
    today: 50,
  },
  {
    moment: "17:00",
    todayForecast: 66,
    lastMonth: 45,
    lastWeek: 40,
    yesterday: 50,
    today: 44,
  },
  {
    moment: "18:00",
    todayForecast: 44,
    lastMonth: 45,
    lastWeek: 50,
    yesterday: 30,
    today: 50,
  },
  {
    moment: "19:00",
    todayForecast: 66,
    lastMonth: 45,
    lastWeek: 40,
    yesterday: 20,
    today: 44,
  },
  {
    moment: "20:00",
    todayForecast: 40,
    lastMonth: 45,
    lastWeek: 50,
    yesterday: 30,
    today: 50,
  }
  ,
  {
    moment: "21:00",
    todayForecast: 47,
    lastMonth: 45,
    lastWeek: 40,
    yesterday: 40,
    today: 44,
  },
  {
    moment: "22:00",
    todayForecast: 40,
    lastMonth: 45,
    lastWeek: 50,
    yesterday: 30,
    today: 50,
  },
  {
    moment: "23:00",
    todayForecast: 60,
    lastMonth: 45,
    lastWeek: 40,
    yesterday: 24,
    today: 44,
  },
  {
    moment: "24:00",
    todayForecast: 40,
    lastMonth: 45,
    lastWeek: 50,
    yesterday: 30,
    today: 50,
  }
];


export const columns3= [
  {
    day: "1",
    thisMonth: 40,
    lastMonth: 45,
    lastyear: 50,
  },
  {
    day: "2",
    thisMonth: 40,
    lastMonth: 45,
    lastyear: 50,
  },
  {
    day: "3",
    thisMonth: 40,
    lastMonth: 45,
    lastyear: 50,
  },
  {
    day: "4",
    thisMonth: 40,
    lastMonth: 45,
    lastyear: 50,
  },
  {
    day: "5",
    thisMonth: 40,
    lastMonth: 45,
    lastyear: 50,
  },
  {
    day: "6",
    thisMonth: 40,
    lastMonth: 45,
    lastyear: 50,
  },
  {
    day: "7",
    thisMonth: 40,
    lastMonth: 45,
    lastyear: 50,
  },
  {
    day: "8",
    thisMonth: 40,
    lastMonth: 45,
    lastyear: 50,
  },
  {
    day: "9",
    thisMonth: 40,
    lastMonth: 45,
    lastyear: 50,
  },
  {
    day: "10",
    thisMonth: 40,
    lastMonth: 45,
    lastyear: 50,
  },
  {
    day: "11",
    thisMonth: 40,
    lastMonth: 45,
    lastyear: 50,
  },
  {
    day: "12",
    thisMonth: 40,
    lastMonth: 45,
    lastyear: 50,
  },
  {
    day: "13",
    thisMonth: 40,
    lastMonth: 45,
    lastyear: 50,
  },
  {
    day: "14",
    thisMonth: 40,
    lastMonth: 45,
    lastyear: 50,
  },
  {
    day: "15",
    thisMonth: 40,
    lastMonth: 45,
    lastyear: 50,
  },
  {
    day: "16",
    thisMonth: 40,
    lastMonth: 45,
    lastyear: 50,
  },
  {
    day: "17",
    thisMonth: 40,
    lastMonth: 45,
    lastyear: 50,
  },
  {
    day: "18",
    thisMonth: 40,
    lastMonth: 45,
    lastyear: 50,
  },
  {
    day: "19",
    thisMonth: 40,
    lastMonth: 45,
    lastyear: 50,
  },
  {
    day: "20",
    thisMonth: 40,
    lastMonth: 45,
    lastyear: 50,
  },
  {
    day: "21",
    thisMonth: 40,
    lastMonth: 45,
    lastyear: 50,
  },
  {
    day: "22",
    thisMonth: 40,
    lastMonth: 45,
    lastyear: 50,
  },
  {
    day: "23",
    thisMonth: 40,
    lastMonth: 45,
    lastyear: 50,
  },
  {
    day: "24",
    thisMonth: 40,
    lastMonth: 45,
    lastyear: 50,
  },
  {
    day: "25",
    thisMonth: 40,
    lastMonth: 45,
    lastyear: 50,
  },
  {
    day: "26",
    thisMonth: 40,
    lastMonth: 45,
    lastyear: 50,
  },
  {
    day: "27",
    thisMonth: 40,
    lastMonth: 45,
    lastyear: 50,
  },
  {
    day: "28",
    thisMonth: 40,
    lastMonth: 45,
    lastyear: 50,
  },
  {
    day: "29",
    thisMonth: 40,
    lastMonth: 45,
    lastyear: 50,
  },
  {
    day: "30",
    thisMonth: 40,
    lastMonth: 45,
    lastyear: 50,
  }
];



export const columns4= [
  {
    month: "1",
    thisYear: 40,
    lastyear: 50,
    beforeYear:30,
  },
  {
    month: "2",
    thisYear: 60,
    lastyear: 40,
    beforeYear:60,
  },
  {
    month: "3",
    thisYear: 40,
    lastyear: 50,
    beforeYear:60,
  },
  {
    month: "4",
    thisYear: 40,
    lastyear: 50,
    beforeYear:60,
  },
  {
    month: "5",
    thisYear: 30,
    lastyear: 70,
    beforeYear:40,
  },
  {
    month: "6",
    thisYear: 40,
    lastyear: 50,
    beforeYear:60,
  },
  {
    month: "7",
    thisYear: 60,
    lastyear: 40,
    beforeYear:50,
  },
  {
    month: "8",
    thisYear: 40,
    lastyear: 50,
    beforeYear:60,
  },
  {
    month: "9",
    thisYear: 30,
    lastyear: 50,
    beforeYear:30,
  },
  {
    month: "10",
    thisYear: 40,
    lastyear: 60,
    beforeYear:60,
  },
  {
    month: "11",
    thisYear: 60,
    lastyear: 50,
    beforeYear:80,
  },
  {
    month: "12",
    thisYear: 40,
    lastyear: 30,
    beforeYear:60,
  },
];
