export const data = {
  LicenseType: 0,
  SGSolverModelName: null,
  SGSolverModelPath: '',
  SGSolverGateStationList: [
    {
      NodeName: '泊里',
      NodeType: 1,
      NodeStatus: 'Known Pressure',
      NodeId: 3643,
      NodePressure: '4000.00',
      NodeFlow: '29224.00',
      NodeReferencePressure: null,
      NodeReferenceFlow: null,
      NodeXCoordinate: '108933.1',
      NodeYCoordinate: '19874.6',
      NodeResultPressure: '4000.00',
      NodeResultFlow: '29224.00',
      NodeDescription: null,
      NodeHigherHeatingValue: 37.26,
      NodeGasStreamComponent: {
        NodeName: '泊里',
        NodeTraceName: '泊里',
        CO2: '0.000000',
        N2: '0.113002',
        C1: '90.045800',
        C2: '7.384148',
        C3: '1.829037',
        C4I: '0.235005',
        C4N: '0.354007',
        C5I: '0.028001',
        C5N: '0.011000',
        C6N: '0.000000',
        C7N: '0.000000',
        C8N: '0.000000',
      },
      NodeFlowProfileNameByCategory: null,
      FlowCategoryList: null,
      GateStationPressureControlType: null,
      GateStationPressureSelect: null,
      GateStationPressureValue: null,
      GateStationFlowSelect: null,
      GateStationFlowValue: null,
    },
    {
      NodeName: '6号阀室',
      NodeType: 1,
      NodeStatus: 'Known Pressure',
      NodeId: 3659,
      NodePressure: '6300.00',
      NodeFlow: '7095.00',
      NodeReferencePressure: null,
      NodeReferenceFlow: null,
      NodeXCoordinate: '150559.2',
      NodeYCoordinate: '30218.6',
      NodeResultPressure: '6300.00',
      NodeResultFlow: '7095.00',
      NodeDescription: null,
      NodeHigherHeatingValue: 37.26,
      NodeGasStreamComponent: {
        NodeName: '6号阀室',
        NodeTraceName: '6号阀室',
        CO2: '0.000000',
        N2: '0.113002',
        C1: '90.045800',
        C2: '7.384148',
        C3: '1.829037',
        C4I: '0.235005',
        C4N: '0.354007',
        C5I: '0.028001',
        C5N: '0.011000',
        C6N: '0.000000',
        C7N: '0.000000',
        C8N: '0.000000',
      },
      NodeFlowProfileNameByCategory: null,
      FlowCategoryList: null,
      GateStationPressureControlType: null,
      GateStationPressureSelect: null,
      GateStationPressureValue: null,
      GateStationFlowSelect: null,
      GateStationFlowValue: null,
    },
    {
      NodeName: '董家口',
      NodeType: 1,
      NodeStatus: 'Known Pressure',
      NodeId: 3666,
      NodePressure: '1600.00',
      NodeFlow: '5000.00',
      NodeReferencePressure: null,
      NodeReferenceFlow: null,
      NodeXCoordinate: '120715.4',
      NodeYCoordinate: '32086.0',
      NodeResultPressure: '1600.00',
      NodeResultFlow: '5000.00',
      NodeDescription: null,
      NodeHigherHeatingValue: 37.26,
      NodeGasStreamComponent: {
        NodeName: '董家口',
        NodeTraceName: '董家口',
        CO2: '0.000000',
        N2: '0.000000',
        C1: '94.560764',
        C2: '4.970970',
        C3: '0.000000',
        C4I: '0.197845',
        C4N: '0.265450',
        C5I: '0.000000',
        C5N: '0.004971',
        C6N: '0.000000',
        C7N: '0.000000',
        C8N: '0.000000',
      },
      NodeFlowProfileNameByCategory: null,
      FlowCategoryList: null,
      GateStationPressureControlType: null,
      GateStationPressureSelect: null,
      GateStationPressureValue: null,
      GateStationFlowSelect: null,
      GateStationFlowValue: null,
    },
    {
      NodeName: '铁山门站',
      NodeType: 1,
      NodeStatus: 'Known Pressure',
      NodeId: 3667,
      NodePressure: '4000.00',
      NodeFlow: '15000.00',
      NodeReferencePressure: null,
      NodeReferenceFlow: null,
      NodeXCoordinate: '118841.6',
      NodeYCoordinate: '40855.2',
      NodeResultPressure: '4000.00',
      NodeResultFlow: '15000.00',
      NodeDescription: null,
      NodeHigherHeatingValue: 37.26,
      NodeGasStreamComponent: {
        NodeName: '铁山门站',
        NodeTraceName: '铁山门站',
        CO2: '0.102006',
        N2: '0.174010',
        C1: '99.575975',
        C2: '0.101006',
        C3: '0.025002',
        C4I: '0.010001',
        C4N: '0.002000',
        C5I: '0.004000',
        C5N: '0.000000',
        C6N: '0.006000',
        C7N: '0.000000',
        C8N: '0.000000',
      },
      NodeFlowProfileNameByCategory: null,
      FlowCategoryList: null,
      GateStationPressureControlType: null,
      GateStationPressureSelect: null,
      GateStationPressureValue: null,
      GateStationFlowSelect: null,
      GateStationFlowValue: null,
    },
  ],
  SGSolverGuestList: [
    {
      NodeName: '团结路门站',
      NodeType: 2,
      NodeStatus: 'Known Flow',
      NodeId: 4331,
      NodePressure: '289.00',
      NodeFlow: '13593.84',
      NodeReferencePressure: '3519.00',
      NodeReferenceFlow: null,
      NodeXCoordinate: '112195.7',
      NodeYCoordinate: '37583.8',
      NodeResultPressure: '289.00',
      NodeResultFlow: '13593.84',
      NodeDescription: null,
      NodeHigherHeatingValue: 37.26,
      NodeGasStreamComponent: null,
      NodeFlowProfileNameByCategory: null,
      FlowCategoryList: null,
      GateStationPressureControlType: null,
      GateStationPressureSelect: null,
      GateStationPressureValue: null,
      GateStationFlowSelect: null,
      GateStationFlowValue: null,
    },
    {
      NodeName: '团结路门站',
      NodeType: 2,
      NodeStatus: 'Known Flow',
      NodeId: 4321,
      NodePressure: '289.00',
      NodeFlow: '13593.84',
      NodeReferencePressure: '3519.00',
      NodeReferenceFlow: null,
      NodeXCoordinate: '112195.7',
      NodeYCoordinate: '37583.8',
      NodeResultPressure: '289.00',
      NodeResultFlow: '13593.84',
      NodeDescription: null,
      NodeHigherHeatingValue: 37.26,
      NodeGasStreamComponent: null,
      NodeFlowProfileNameByCategory: null,
      FlowCategoryList: null,
      GateStationPressureControlType: null,
      GateStationPressureSelect: null,
      GateStationPressureValue: null,
      GateStationFlowSelect: null,
      GateStationFlowValue: null,
    },
    {
      NodeName: '红石崖门站',
      NodeType: 2,
      NodeStatus: 'Known Flow',
      NodeId: 4234,
      NodePressure: '389.1',
      NodeFlow: '10859.953',
      NodeReferencePressure: '3519.00',
      NodeReferenceFlow: null,
      NodeXCoordinate: '112195.7',
      NodeYCoordinate: '37583.8',
      NodeResultPressure: '389.1',
      NodeResultFlow: '10859.953',
      NodeDescription: null,
      NodeHigherHeatingValue: 37.26,
      NodeGasStreamComponent: null,
      NodeFlowProfileNameByCategory: null,
      FlowCategoryList: null,
      GateStationPressureControlType: null,
      GateStationPressureSelect: null,
      GateStationPressureValue: null,
      GateStationFlowSelect: null,
      GateStationFlowValue: null,
    },

    {
      NodeName: '大炼油',
      NodeType: 2,
      NodeStatus: 'Known Flow',
      NodeId: 4235,
      NodePressure: '324.94',
      NodeFlow: '8333.076',
      NodeReferencePressure: '3519.00',
      NodeReferenceFlow: null,
      NodeXCoordinate: '112195.7',
      NodeYCoordinate: '37583.8',
      NodeResultPressure: '324.94',
      NodeResultFlow: '8333.076',
      NodeDescription: null,
      NodeHigherHeatingValue: 37.26,
      NodeGasStreamComponent: null,
      NodeFlowProfileNameByCategory: null,
      FlowCategoryList: null,
      GateStationPressureControlType: null,
      GateStationPressureSelect: null,
      GateStationPressureValue: null,
      GateStationFlowSelect: null,
      GateStationFlowValue: null,
    },

    {
      NodeName: '灵山卫无人值守站',
      NodeType: 2,
      NodeStatus: 'Known Flow',
      NodeId: 4236,
      NodePressure: '272.00',
      NodeFlow: '2469.632',
      NodeReferencePressure: '3519.00',
      NodeReferenceFlow: null,
      NodeXCoordinate: '112195.7',
      NodeYCoordinate: '37583.8',
      NodeResultPressure: '272.00',
      NodeResultFlow: '2469.632',
      NodeDescription: null,
      NodeHigherHeatingValue: 37.26,
      NodeGasStreamComponent: null,
      NodeFlowProfileNameByCategory: null,
      FlowCategoryList: null,
      GateStationPressureControlType: null,
      GateStationPressureSelect: null,
      GateStationPressureValue: null,
      GateStationFlowSelect: null,
      GateStationFlowValue: null,
    },

    {
      NodeName: '王台无人站',
      NodeType: 2,
      NodeStatus: 'Known Flow',
      NodeId: 4237,
      NodePressure: '255.32',
      NodeFlow: '2169.163',
      NodeReferencePressure: '3519.00',
      NodeReferenceFlow: null,
      NodeXCoordinate: '112195.7',
      NodeYCoordinate: '37583.8',
      NodeResultPressure: '255.32',
      NodeResultFlow: '2169.163',
      NodeDescription: null,
      NodeHigherHeatingValue: 37.26,
      NodeGasStreamComponent: null,
      NodeFlowProfileNameByCategory: null,
      FlowCategoryList: null,
      GateStationPressureControlType: null,
      GateStationPressureSelect: null,
      GateStationPressureValue: null,
      GateStationFlowSelect: null,
      GateStationFlowValue: null,
    },

    {
      NodeName: '武船LNG',
      NodeType: 2,
      NodeStatus: 'Known Flow',
      NodeId: 4238,
      NodePressure: '195.00',
      NodeFlow: '1406.082',
      NodeReferencePressure: '3519.00',
      NodeReferenceFlow: null,
      NodeXCoordinate: '112195.7',
      NodeYCoordinate: '37583.8',
      NodeResultPressure: '195.00',
      NodeResultFlow: '1406.082',
      NodeDescription: null,
      NodeHigherHeatingValue: 37.26,
      NodeGasStreamComponent: null,
      NodeFlowProfileNameByCategory: null,
      FlowCategoryList: null,
      GateStationPressureControlType: null,
      GateStationPressureSelect: null,
      GateStationPressureValue: null,
      GateStationFlowSelect: null,
      GateStationFlowValue: null,
    },

    {
      NodeName: '黄山无人站',
      NodeType: 2,
      NodeStatus: 'Known Flow',
      NodeId: 4239,
      NodePressure: '280.00',
      NodeFlow: '624.577',
      NodeReferencePressure: '3519.00',
      NodeReferenceFlow: null,
      NodeXCoordinate: '112195.7',
      NodeYCoordinate: '37583.8',
      NodeResultPressure: '280.00',
      NodeResultFlow: '624.577',
      NodeDescription: null,
      NodeHigherHeatingValue: 37.26,
      NodeGasStreamComponent: null,
      NodeFlowProfileNameByCategory: null,
      FlowCategoryList: null,
      GateStationPressureControlType: null,
      GateStationPressureSelect: null,
      GateStationPressureValue: null,
      GateStationFlowSelect: null,
      GateStationFlowValue: null,
    },

    {
      NodeName: '山前无人站',
      NodeType: 2,
      NodeStatus: 'Known Flow',
      NodeId: 4240,
      NodePressure: '280.0',
      NodeFlow: '458.519',
      NodeReferencePressure: '3519.00',
      NodeReferenceFlow: null,
      NodeXCoordinate: '112195.7',
      NodeYCoordinate: '37583.8',
      NodeResultPressure: '280.0',
      NodeResultFlow: '458.519',
      NodeDescription: null,
      NodeHigherHeatingValue: 37.26,
      NodeGasStreamComponent: null,
      NodeFlowProfileNameByCategory: null,
      FlowCategoryList: null,
      GateStationPressureControlType: null,
      GateStationPressureSelect: null,
      GateStationPressureValue: null,
      GateStationFlowSelect: null,
      GateStationFlowValue: null,
    },
  ],
  SGSolverDeviceValveList: [
    {
      ValveName: '安托山阀门',
      ValveStatus: true,
    },
    {
      ValveName: '安托山1',
      ValveStatus: true,
    },
    {
      ValveName: '坪山西二线',
      ValveStatus: false,
    },
    {
      ValveName: '坪山大鹏进口',
      ValveStatus: true,
    },
    {
      ValveName: '求雨岭',
      ValveStatus: true,
    },
    {
      ValveName: '坪山调压器进口',
      ValveStatus: false,
    },
    {
      ValveName: '气库',
      ValveStatus: false,
    },
    {
      ValveName: '安托山2',
      ValveStatus: true,
    },
    {
      ValveName: '阀门130',
      ValveStatus: true,
    },
    {
      ValveName: '阀90474',
      ValveStatus: true,
    },
  ],
  SGSolverDeviceRegulatorList: [
    {
      RegulatorName: '留仙洞高-次高调压站',
      RegulatorValue: 1450,
    },
    {
      RegulatorName: '求雨岭站至次高',
      RegulatorValue: 1450,
    },
    {
      RegulatorName: '安托山东调压器',
      RegulatorValue: 1406,
    },
    {
      RegulatorName: '安托山西调压器',
      RegulatorValue: 1406,
    },
    {
      RegulatorName: '安托山调压器',
      RegulatorValue: 3945,
    },
    {
      RegulatorName: '坪山调压器',
      RegulatorValue: 3900,
    },
    {
      RegulatorName: '气库1',
      RegulatorValue: 1450,
    },
    {
      RegulatorName: '坪山7',
      RegulatorValue: 1383,
    },
    {
      RegulatorName: '调压120110',
      RegulatorValue: 3900,
    },
    {
      RegulatorName: '调压120111',
      RegulatorValue: 3900,
    },
    {
      RegulatorName: '求雨岭门站',
      RegulatorValue: 3900,
    },
  ],
}

export const simulationData = {
  LicenseType: 0,
  SGSolverModelName: null,
  SGSolverModelPath: null,
  SGSolverGateStationList: [
    {
      NodeName: '泊里',
      NodeType: 1,
      NodeStatus: 'Known Pressure',
      NodeId: 3643,
      NodePressure: '4000.00',
      NodeFlow: '29224.00',
      NodeReferencePressure: null,
      NodeReferenceFlow: null,
      NodeXCoordinate: '108933.1',
      NodeYCoordinate: '19874.6',
      NodeResultPressure: '4000.00',
      NodeResultFlow: '29224.00',
      NodeDescription: null,
      NodeHigherHeatingValue: 37.26,
      NodeGasStreamComponent: {
        NodeName: '泊里',
        NodeTraceName: '泊里',
        CO2: '0.000000',
        N2: '0.113002',
        C1: '90.045800',
        C2: '7.384148',
        C3: '1.829037',
        C4I: '0.235005',
        C4N: '0.354007',
        C5I: '0.028001',
        C5N: '0.011000',
        C6N: '0.000000',
        C7N: '0.000000',
        C8N: '0.000000',
      },
      SGSolverProfileList: null,
      FlowCategoryList: null,
      GateStationPressureControlType: null,
      GateStationPressureSelect: null,
      GateStationPressureValue: null,
      GateStationFlowSelect: null,
      GateStationFlowValue: null,
    },
    {
      NodeName: '6号阀室',
      NodeType: 1,
      NodeStatus: 'Known Pressure',
      NodeId: 3659,
      NodePressure: '6300.00',
      NodeFlow: '7095.00',
      NodeReferencePressure: null,
      NodeReferenceFlow: null,
      NodeXCoordinate: '150559.2',
      NodeYCoordinate: '30218.6',
      NodeResultPressure: '6300.00',
      NodeResultFlow: '7095.00',
      NodeDescription: null,
      NodeHigherHeatingValue: 37.26,
      NodeGasStreamComponent: {
        NodeName: '6号阀室',
        NodeTraceName: '6号阀室',
        CO2: '0.000000',
        N2: '0.113002',
        C1: '90.045800',
        C2: '7.384148',
        C3: '1.829037',
        C4I: '0.235005',
        C4N: '0.354007',
        C5I: '0.028001',
        C5N: '0.011000',
        C6N: '0.000000',
        C7N: '0.000000',
        C8N: '0.000000',
      },
      SGSolverProfileList: null,
      FlowCategoryList: null,
      GateStationPressureControlType: null,
      GateStationPressureSelect: null,
      GateStationPressureValue: null,
      GateStationFlowSelect: null,
      GateStationFlowValue: null,
    },
    {
      NodeName: '董家口',
      NodeType: 1,
      NodeStatus: 'Known Pressure',
      NodeId: 3666,
      NodePressure: '1600.00',
      NodeFlow: '1600.00',
      NodeReferencePressure: null,
      NodeReferenceFlow: null,
      NodeXCoordinate: '120715.4',
      NodeYCoordinate: '32086.0',
      NodeResultPressure: '1600.00',
      NodeResultFlow: '1600.00',
      NodeDescription: null,
      NodeHigherHeatingValue: 37.26,
      NodeGasStreamComponent: {
        NodeName: '董家口',
        NodeTraceName: '董家口',
        CO2: '0.000000',
        N2: '0.000000',
        C1: '94.560764',
        C2: '4.970970',
        C3: '0.000000',
        C4I: '0.197845',
        C4N: '0.265450',
        C5I: '0.000000',
        C5N: '0.004971',
        C6N: '0.000000',
        C7N: '0.000000',
        C8N: '0.000000',
      },
      SGSolverProfileList: null,
      FlowCategoryList: null,
      GateStationPressureControlType: null,
      GateStationPressureSelect: null,
      GateStationPressureValue: null,
      GateStationFlowSelect: null,
      GateStationFlowValue: null,
    },
    {
      NodeName: '铁山门站',
      NodeType: 1,
      NodeStatus: 'Known Pressure',
      NodeId: 3667,
      NodePressure: '4000.00',
      NodeFlow: '15000.00',
      NodeReferencePressure: null,
      NodeReferenceFlow: null,
      NodeXCoordinate: '118841.6',
      NodeYCoordinate: '40855.2',
      NodeResultPressure: '4000.00',
      NodeResultFlow: '15000.00',
      NodeDescription: null,
      NodeHigherHeatingValue: 37.68,
      NodeGasStreamComponent: {
        NodeName: '铁山门站',
        NodeTraceName: '铁山门站',
        CO2: '0.102006',
        N2: '0.174010',
        C1: '99.575975',
        C2: '0.101006',
        C3: '0.025002',
        C4I: '0.010001',
        C4N: '0.002000',
        C5I: '0.004000',
        C5N: '0.000000',
        C6N: '0.006000',
        C7N: '0.000000',
        C8N: '0.000000',
      },
      SGSolverProfileList: null,
      FlowCategoryList: null,
      GateStationPressureControlType: null,
      GateStationPressureSelect: null,
      GateStationPressureValue: null,
      GateStationFlowSelect: null,
      GateStationFlowValue: null,
    },
  ],
  SGSolverGuestList: [
    {
      NodeName: '团结路门站',
      NodeType: 2,
      NodeStatus: 'Known Flow',
      NodeId: 4331,
      NodePressure: '289.00',
      NodeFlow: '13593.84',
      NodeReferencePressure: '3519.00',
      NodeReferenceFlow: null,
      NodeXCoordinate: '112195.7',
      NodeYCoordinate: '37583.8',
      NodeResultPressure: '289.00',
      NodeResultFlow: '13593.84',
      NodeDescription: null,
      NodeHigherHeatingValue: 37.26,
      NodeGasStreamComponent: null,
      NodeFlowProfileNameByCategory: null,
      FlowCategoryList: null,
      GateStationPressureControlType: null,
      GateStationPressureSelect: null,
      GateStationPressureValue: null,
      GateStationFlowSelect: null,
      GateStationFlowValue: null,
    },

    {
      NodeName: '红石崖门站',
      NodeType: 2,
      NodeStatus: 'Known Flow',
      NodeId: 4234,
      NodePressure: '389.1',
      NodeFlow: '10859.953',
      NodeReferencePressure: '3519.00',
      NodeReferenceFlow: null,
      NodeXCoordinate: '112195.7',
      NodeYCoordinate: '37583.8',
      NodeResultPressure: '389.1',
      NodeResultFlow: '10859.953',
      NodeDescription: null,
      NodeHigherHeatingValue: 37.26,
      NodeGasStreamComponent: null,
      NodeFlowProfileNameByCategory: null,
      FlowCategoryList: null,
      GateStationPressureControlType: null,
      GateStationPressureSelect: null,
      GateStationPressureValue: null,
      GateStationFlowSelect: null,
      GateStationFlowValue: null,
    },

    {
      NodeName: '大炼油',
      NodeType: 2,
      NodeStatus: 'Known Flow',
      NodeId: 4235,
      NodePressure: '324.94',
      NodeFlow: '8333.076',
      NodeReferencePressure: '3519.00',
      NodeReferenceFlow: null,
      NodeXCoordinate: '112195.7',
      NodeYCoordinate: '37583.8',
      NodeResultPressure: '324.94',
      NodeResultFlow: '8333.076',
      NodeDescription: null,
      NodeHigherHeatingValue: 37.26,
      NodeGasStreamComponent: null,
      NodeFlowProfileNameByCategory: null,
      FlowCategoryList: null,
      GateStationPressureControlType: null,
      GateStationPressureSelect: null,
      GateStationPressureValue: null,
      GateStationFlowSelect: null,
      GateStationFlowValue: null,
    },

    {
      NodeName: '灵山卫无人值守站',
      NodeType: 2,
      NodeStatus: 'Known Flow',
      NodeId: 4236,
      NodePressure: '272.00',
      NodeFlow: '2469.632',
      NodeReferencePressure: '3519.00',
      NodeReferenceFlow: null,
      NodeXCoordinate: '112195.7',
      NodeYCoordinate: '37583.8',
      NodeResultPressure: '272.00',
      NodeResultFlow: '2469.632',
      NodeDescription: null,
      NodeHigherHeatingValue: 37.26,
      NodeGasStreamComponent: null,
      NodeFlowProfileNameByCategory: null,
      FlowCategoryList: null,
      GateStationPressureControlType: null,
      GateStationPressureSelect: null,
      GateStationPressureValue: null,
      GateStationFlowSelect: null,
      GateStationFlowValue: null,
    },

    {
      NodeName: '王台无人站',
      NodeType: 2,
      NodeStatus: 'Known Flow',
      NodeId: 4237,
      NodePressure: '255.32',
      NodeFlow: '2169.163',
      NodeReferencePressure: '3519.00',
      NodeReferenceFlow: null,
      NodeXCoordinate: '112195.7',
      NodeYCoordinate: '37583.8',
      NodeResultPressure: '255.32',
      NodeResultFlow: '2169.163',
      NodeDescription: null,
      NodeHigherHeatingValue: 37.26,
      NodeGasStreamComponent: null,
      NodeFlowProfileNameByCategory: null,
      FlowCategoryList: null,
      GateStationPressureControlType: null,
      GateStationPressureSelect: null,
      GateStationPressureValue: null,
      GateStationFlowSelect: null,
      GateStationFlowValue: null,
    },

    {
      NodeName: '武船LNG',
      NodeType: 2,
      NodeStatus: 'Known Flow',
      NodeId: 4238,
      NodePressure: '195.00',
      NodeFlow: '1406.082',
      NodeReferencePressure: '3519.00',
      NodeReferenceFlow: null,
      NodeXCoordinate: '112195.7',
      NodeYCoordinate: '37583.8',
      NodeResultPressure: '195.00',
      NodeResultFlow: '1406.082',
      NodeDescription: null,
      NodeHigherHeatingValue: 37.26,
      NodeGasStreamComponent: null,
      NodeFlowProfileNameByCategory: null,
      FlowCategoryList: null,
      GateStationPressureControlType: null,
      GateStationPressureSelect: null,
      GateStationPressureValue: null,
      GateStationFlowSelect: null,
      GateStationFlowValue: null,
    },

    {
      NodeName: '黄山无人站',
      NodeType: 2,
      NodeStatus: 'Known Flow',
      NodeId: 4239,
      NodePressure: '280.00',
      NodeFlow: '624.577',
      NodeReferencePressure: '3519.00',
      NodeReferenceFlow: null,
      NodeXCoordinate: '112195.7',
      NodeYCoordinate: '37583.8',
      NodeResultPressure: '280.00',
      NodeResultFlow: '624.577',
      NodeDescription: null,
      NodeHigherHeatingValue: 37.26,
      NodeGasStreamComponent: null,
      NodeFlowProfileNameByCategory: null,
      FlowCategoryList: null,
      GateStationPressureControlType: null,
      GateStationPressureSelect: null,
      GateStationPressureValue: null,
      GateStationFlowSelect: null,
      GateStationFlowValue: null,
    },

    {
      NodeName: '山前无人站',
      NodeType: 2,
      NodeStatus: 'Known Flow',
      NodeId: 4240,
      NodePressure: '280.0',
      NodeFlow: '458.519',
      NodeReferencePressure: '3519.00',
      NodeReferenceFlow: null,
      NodeXCoordinate: '112195.7',
      NodeYCoordinate: '37583.8',
      NodeResultPressure: '280.0',
      NodeResultFlow: '458.519',
      NodeDescription: null,
      NodeHigherHeatingValue: 37.26,
      NodeGasStreamComponent: null,
      NodeFlowProfileNameByCategory: null,
      FlowCategoryList: null,
      GateStationPressureControlType: null,
      GateStationPressureSelect: null,
      GateStationPressureValue: null,
      GateStationFlowSelect: null,
      GateStationFlowValue: null,
    },
  ],

  SGSolverGuestEastUserList: [
    {
      NodeName: '天物金柏',
      NodeType: 2,
      NodeStatus: 'Known Flow',
      NodeId: 4240,
      NodePressure: '247.76',
      NodeFlow: '-1137',
      NodeReferencePressure: '3519.00',
      NodeReferenceFlow: null,
      NodeXCoordinate: '112195.7',
      NodeYCoordinate: '37583.8',
      NodeResultPressure: '247.76',
      NodeResultFlow: '-1137',
      NodeDescription: null,
      NodeHigherHeatingValue: 37.26,
      NodeGasStreamComponent: null,
      NodeFlowProfileNameByCategory: null,
      FlowCategoryList: null,
      GateStationPressureControlType: null,
      GateStationPressureSelect: null,
      GateStationPressureValue: null,
      GateStationFlowSelect: null,
      GateStationFlowValue: null,
    },

    {
      NodeName: '1号泛能站',
      NodeType: 2,
      NodeStatus: 'Known Flow',
      NodeId: 4243,
      NodePressure: '298.03',
      NodeFlow: '-884.19',
      NodeReferencePressure: '3519.00',
      NodeReferenceFlow: null,
      NodeXCoordinate: '112195.7',
      NodeYCoordinate: '37583.8',
      NodeResultPressure: '298.03',
      NodeResultFlow: '-884.19',
      NodeDescription: null,
      NodeHigherHeatingValue: 37.26,
      NodeGasStreamComponent: null,
      NodeFlowProfileNameByCategory: null,
      FlowCategoryList: null,
      GateStationPressureControlType: null,
      GateStationPressureSelect: null,
      GateStationPressureValue: null,
      GateStationFlowSelect: null,
      GateStationFlowValue: null,
    },

    {
      NodeName: '二期锅炉',
      NodeType: 2,
      NodeStatus: 'Known Flow',
      NodeId: 4244,
      NodePressure: '317.64',
      NodeFlow: '-680.8',
      NodeReferencePressure: '3519.00',
      NodeReferenceFlow: null,
      NodeXCoordinate: '112195.7',
      NodeYCoordinate: '37583.8',
      NodeResultPressure: '317.64',
      NodeResultFlow: '-680.8',
      NodeDescription: null,
      NodeHigherHeatingValue: 37.26,
      NodeGasStreamComponent: null,
      NodeFlowProfileNameByCategory: null,
      FlowCategoryList: null,
      GateStationPressureControlType: null,
      GateStationPressureSelect: null,
      GateStationPressureValue: null,
      GateStationFlowSelect: null,
      GateStationFlowValue: null,
    },

    {
      NodeName: '松花江路 安迈二期 1',
      NodeType: 2,
      NodeStatus: 'Known Flow',
      NodeId: 4245,
      NodePressure: '247.76',
      NodeFlow: '-268.6',
      NodeReferencePressure: '3519.00',
      NodeReferenceFlow: null,
      NodeXCoordinate: '112195.7',
      NodeYCoordinate: '37583.8',
      NodeResultPressure: '268.6',
      NodeResultFlow: '-655.805',
      NodeDescription: null,
      NodeHigherHeatingValue: 37.26,
      NodeGasStreamComponent: null,
      NodeFlowProfileNameByCategory: null,
      FlowCategoryList: null,
      GateStationPressureControlType: null,
      GateStationPressureSelect: null,
      GateStationPressureValue: null,
      GateStationFlowSelect: null,
      GateStationFlowValue: null,
    },

    {
      NodeName: '上汽五菱',
      NodeType: 2,
      NodeStatus: 'Known Flow',
      NodeId: 4246,
      NodePressure: '258.9',
      NodeFlow: '-632.083',
      NodeReferencePressure: '3519.00',
      NodeReferenceFlow: null,
      NodeXCoordinate: '112195.7',
      NodeYCoordinate: '37583.8',
      NodeResultPressure: '258.9',
      NodeResultFlow: '-632.083',
      NodeDescription: null,
      NodeHigherHeatingValue: 37.26,
      NodeGasStreamComponent: null,
      NodeFlowProfileNameByCategory: null,
      FlowCategoryList: null,
      GateStationPressureControlType: null,
      GateStationPressureSelect: null,
      GateStationPressureValue: null,
      GateStationFlowSelect: null,
      GateStationFlowValue: null,
    },

    {
      NodeName: '金晶玻璃',
      NodeType: 2,
      NodeStatus: 'Known Flow',
      NodeId: 4247,
      NodePressure: '300.41',
      NodeFlow: '-598.065',
      NodeReferencePressure: '3519.00',
      NodeReferenceFlow: null,
      NodeXCoordinate: '112195.7',
      NodeYCoordinate: '37583.8',
      NodeResultPressure: '300.41',
      NodeResultFlow: '-598.065',
      NodeDescription: null,
      NodeHigherHeatingValue: 37.26,
      NodeGasStreamComponent: null,
      NodeFlowProfileNameByCategory: null,
      FlowCategoryList: null,
      GateStationPressureControlType: null,
      GateStationPressureSelect: null,
      GateStationPressureValue: null,
      GateStationFlowSelect: null,
      GateStationFlowValue: null,
    },

    {
      NodeName: '惠城科技',
      NodeType: 2,
      NodeStatus: 'Known Flow',
      NodeId: 4248,
      NodePressure: '289.79',
      NodeFlow: '-577.802',
      NodeReferencePressure: '3519.00',
      NodeReferenceFlow: null,
      NodeXCoordinate: '112195.7',
      NodeYCoordinate: '37583.8',
      NodeResultPressure: '289.79',
      NodeResultFlow: '-577.802',
      NodeDescription: null,
      NodeHigherHeatingValue: 37.26,
      NodeGasStreamComponent: null,
      NodeFlowProfileNameByCategory: null,
      FlowCategoryList: null,
      GateStationPressureControlType: null,
      GateStationPressureSelect: null,
      GateStationPressureValue: null,
      GateStationFlowSelect: null,
      GateStationFlowValue: null,
    },

    {
      NodeName: '圣戈班油改气',
      NodeType: 2,
      NodeStatus: 'Known Flow',
      NodeId: 4249,
      NodePressure: '317.44',
      NodeFlow: '-1030',
      NodeReferencePressure: '3519.00',
      NodeReferenceFlow: null,
      NodeXCoordinate: '112195.7',
      NodeYCoordinate: '37583.8',
      NodeResultPressure: '317.44',
      NodeResultFlow: '-1030',
      NodeDescription: null,
      NodeHigherHeatingValue: 37.26,
      NodeGasStreamComponent: null,
      NodeFlowProfileNameByCategory: null,
      FlowCategoryList: null,
      GateStationPressureControlType: null,
      GateStationPressureSelect: null,
      GateStationPressureValue: null,
      GateStationFlowSelect: null,
      GateStationFlowValue: null,
    },

    {
      NodeName: '邱博',
      NodeType: 2,
      NodeStatus: 'Known Flow',
      NodeId: 4250,
      NodePressure: '305.41',
      NodeFlow: '-521.328',
      NodeReferencePressure: '3519.00',
      NodeReferenceFlow: null,
      NodeXCoordinate: '112195.7',
      NodeYCoordinate: '37583.8',
      NodeResultPressure: '305.41',
      NodeResultFlow: '-521.328',
      NodeDescription: null,
      NodeHigherHeatingValue: 37.26,
      NodeGasStreamComponent: null,
      NodeFlowProfileNameByCategory: null,
      FlowCategoryList: null,
      GateStationPressureControlType: null,
      GateStationPressureSelect: null,
      GateStationPressureValue: null,
      GateStationFlowSelect: null,
      GateStationFlowValue: null,
    },
  ],
  SGSolverGuestWestSupplyList: [
    {
      NodeName: '胶南临港门站',
      NodeType: 2,
      NodeStatus: 'Known Flow',
      NodeId: 4251,
      NodePressure: '352.0',
      NodeFlow: '14000.00',
      NodeReferencePressure: '3519.00',
      NodeReferenceFlow: null,
      NodeXCoordinate: '112195.7',
      NodeYCoordinate: '37583.8',
      NodeResultPressure: '352.0',
      NodeResultFlow: '14000.00',
      NodeDescription: null,
      NodeHigherHeatingValue: 37.26,
      NodeGasStreamComponent: null,
      NodeFlowProfileNameByCategory: null,
      FlowCategoryList: null,
      GateStationPressureControlType: null,
      GateStationPressureSelect: null,
      GateStationPressureValue: null,
      GateStationFlowSelect: null,
      GateStationFlowValue: null,
    },
    {
      NodeName: '大珠山',
      NodeType: 2,
      NodeStatus: 'Known Flow',
      NodeId: 4252,
      NodePressure: '266.0',
      NodeFlow: '1000',
      NodeReferencePressure: '3519.00',
      NodeReferenceFlow: null,
      NodeXCoordinate: '112195.7',
      NodeYCoordinate: '37583.8',
      NodeResultPressure: '266.0',
      NodeResultFlow: '1000',
      NodeDescription: null,
      NodeHigherHeatingValue: 37.26,
      NodeGasStreamComponent: null,
      NodeFlowProfileNameByCategory: null,
      FlowCategoryList: null,
      GateStationPressureControlType: null,
      GateStationPressureSelect: null,
      GateStationPressureValue: null,
      GateStationFlowSelect: null,
      GateStationFlowValue: null,
    },
    {
      NodeName: '开城路（规划未来)',
      NodeType: 2,
      NodeStatus: 'Known Flow',
      NodeId: 4253,
      NodePressure: '350.0',
      NodeFlow: '5000',
      NodeReferencePressure: '3519.00',
      NodeReferenceFlow: null,
      NodeXCoordinate: '112195.7',
      NodeYCoordinate: '37583.8',
      NodeResultPressure: '350.0',
      NodeResultFlow: '5000',
      NodeDescription: null,
      NodeHigherHeatingValue: 37.26,
      NodeGasStreamComponent: null,
      NodeFlowProfileNameByCategory: null,
      FlowCategoryList: null,
      GateStationPressureControlType: null,
      GateStationPressureSelect: null,
      GateStationPressureValue: null,
      GateStationFlowSelect: null,
      GateStationFlowValue: null,
    },

    {
      NodeName: '铁山（规划未来）',
      NodeType: 2,
      NodeStatus: 'Known Flow',
      NodeId: 4254,
      NodePressure: '350.0',
      NodeFlow: '5000',
      NodeReferencePressure: '3519.00',
      NodeReferenceFlow: null,
      NodeXCoordinate: '112195.7',
      NodeYCoordinate: '37583.8',
      NodeResultPressure: '350.0',
      NodeResultFlow: '5000',
      NodeDescription: null,
      NodeHigherHeatingValue: 37.26,
      NodeGasStreamComponent: null,
      NodeFlowProfileNameByCategory: null,
      FlowCategoryList: null,
      GateStationPressureControlType: null,
      GateStationPressureSelect: null,
      GateStationPressureValue: null,
      GateStationFlowSelect: null,
      GateStationFlowValue: null,
    },
  ],

  SGSolverGuestWestUserList: [
    {
      NodeName: '秦家庄小区',
      NodeType: 2,
      NodeStatus: 'Known Flow',
      NodeId: 4260,
      NodePressure: '269.8',
      NodeFlow: '458.519',
      NodeReferencePressure: '3519.00',
      NodeReferenceFlow: null,
      NodeXCoordinate: '112195.7',
      NodeYCoordinate: '37583.8',
      NodeResultPressure: '269.8',
      NodeResultFlow: '458.519',
      NodeDescription: null,
      NodeHigherHeatingValue: 37.26,
      NodeGasStreamComponent: null,
      NodeFlowProfileNameByCategory: null,
      FlowCategoryList: null,
      GateStationPressureControlType: null,
      GateStationPressureSelect: null,
      GateStationPressureValue: null,
      GateStationFlowSelect: null,
      GateStationFlowValue: null,
    },
    {
      NodeName: '凤凰社区调压柜',
      NodeType: 2,
      NodeStatus: 'Known Flow',
      NodeId: 4261,
      NodePressure: '206.31',
      NodeFlow: '458.519',
      NodeReferencePressure: '3519.00',
      NodeReferenceFlow: null,
      NodeXCoordinate: '112195.7',
      NodeYCoordinate: '37583.8',
      NodeResultPressure: '206.31',
      NodeResultFlow: '458.519',
      NodeDescription: null,
      NodeHigherHeatingValue: 37.26,
      NodeGasStreamComponent: null,
      NodeFlowProfileNameByCategory: null,
      FlowCategoryList: null,
      GateStationPressureControlType: null,
      GateStationPressureSelect: null,
      GateStationPressureValue: null,
      GateStationFlowSelect: null,
      GateStationFlowValue: null,
    },
    {
      NodeName: '镜川食品调压柜',
      NodeType: 2,
      NodeStatus: 'Known Flow',
      NodeId: 4262,
      NodePressure: '169.51',
      NodeFlow: '458.519',
      NodeReferencePressure: '3519.00',
      NodeReferenceFlow: null,
      NodeXCoordinate: '112195.7',
      NodeYCoordinate: '37583.8',
      NodeResultPressure: '169.51',
      NodeResultFlow: '458.519',
      NodeDescription: null,
      NodeHigherHeatingValue: 37.26,
      NodeGasStreamComponent: null,
      NodeFlowProfileNameByCategory: null,
      FlowCategoryList: null,
      GateStationPressureControlType: null,
      GateStationPressureSelect: null,
      GateStationPressureValue: null,
      GateStationFlowSelect: null,
      GateStationFlowValue: null,
    },
    {
      NodeName: '大溪谷',
      NodeType: 2,
      NodeStatus: 'Known Flow',
      NodeId: 4263,
      NodePressure: '331.21',
      NodeFlow: '458.519',
      NodeReferencePressure: '3519.00',
      NodeReferenceFlow: null,
      NodeXCoordinate: '112195.7',
      NodeYCoordinate: '37583.8',
      NodeResultPressure: '331.21',
      NodeResultFlow: '458.519',
      NodeDescription: null,
      NodeHigherHeatingValue: 37.26,
      NodeGasStreamComponent: null,
      NodeFlowProfileNameByCategory: null,
      FlowCategoryList: null,
      GateStationPressureControlType: null,
      GateStationPressureSelect: null,
      GateStationPressureValue: null,
      GateStationFlowSelect: null,
      GateStationFlowValue: null,
    },
    {
      NodeName: '海之韵四期',
      NodeType: 2,
      NodeStatus: 'Known Flow',
      NodeId: 4264,
      NodePressure: '214.25',
      NodeFlow: '458.519',
      NodeReferencePressure: '3519.00',
      NodeReferenceFlow: null,
      NodeXCoordinate: '112195.7',
      NodeYCoordinate: '37583.8',
      NodeResultPressure: '214.25',
      NodeResultFlow: '458.519',
      NodeDescription: null,
      NodeHigherHeatingValue: 37.26,
      NodeGasStreamComponent: null,
      NodeFlowProfileNameByCategory: null,
      FlowCategoryList: null,
      GateStationPressureControlType: null,
      GateStationPressureSelect: null,
      GateStationPressureValue: null,
      GateStationFlowSelect: null,
      GateStationFlowValue: null,
    },
    {
      NodeName: '凤凰山路光大构件',
      NodeType: 2,
      NodeStatus: 'Known Flow',
      NodeId: 4265,
      NodePressure: '332.48',
      NodeFlow: '458.519',
      NodeReferencePressure: '3519.00',
      NodeReferenceFlow: null,
      NodeXCoordinate: '112195.7',
      NodeYCoordinate: '37583.8',
      NodeResultPressure: '332.48',
      NodeResultFlow: '458.519',
      NodeDescription: null,
      NodeHigherHeatingValue: 37.26,
      NodeGasStreamComponent: null,
      NodeFlowProfileNameByCategory: null,
      FlowCategoryList: null,
      GateStationPressureControlType: null,
      GateStationPressureSelect: null,
      GateStationPressureValue: null,
      GateStationFlowSelect: null,
      GateStationFlowValue: null,
    },
    {
      NodeName: '自峄山路东亚轮胎',
      NodeType: 2,
      NodeStatus: 'Known Flow',
      NodeId: 4266,
      NodePressure: '237.82',
      NodeFlow: '458.519',
      NodeReferencePressure: '3519.00',
      NodeReferenceFlow: null,
      NodeXCoordinate: '112195.7',
      NodeYCoordinate: '37583.8',
      NodeResultPressure: '237.82',
      NodeResultFlow: '458.519',
      NodeDescription: null,
      NodeHigherHeatingValue: 37.26,
      NodeGasStreamComponent: null,
      NodeFlowProfileNameByCategory: null,
      FlowCategoryList: null,
      GateStationPressureControlType: null,
      GateStationPressureSelect: null,
      GateStationPressureValue: null,
      GateStationFlowSelect: null,
      GateStationFlowValue: null,
    },
    {
      NodeName: '东元路鑫森工具',
      NodeType: 2,
      NodeStatus: 'Known Flow',
      NodeId: 4267,
      NodePressure: '334.89',
      NodeFlow: '458.519',
      NodeReferencePressure: '3519.00',
      NodeReferenceFlow: null,
      NodeXCoordinate: '112195.7',
      NodeYCoordinate: '37583.8',
      NodeResultPressure: '334.89',
      NodeResultFlow: '458.519',
      NodeDescription: null,
      NodeHigherHeatingValue: 37.26,
      NodeGasStreamComponent: null,
      NodeFlowProfileNameByCategory: null,
      FlowCategoryList: null,
      GateStationPressureControlType: null,
      GateStationPressureSelect: null,
      GateStationPressureValue: null,
      GateStationFlowSelect: null,
      GateStationFlowValue: null,
    },
    {
      NodeName: '东岳东路浪琴海',
      NodeType: 2,
      NodeStatus: 'Known Flow',
      NodeId: 4268,
      NodePressure: '300.97',
      NodeFlow: '458.519',
      NodeReferencePressure: '3519.00',
      NodeReferenceFlow: null,
      NodeXCoordinate: '112195.7',
      NodeYCoordinate: '37583.8',
      NodeResultPressure: '300.97',
      NodeResultFlow: '458.519',
      NodeDescription: null,
      NodeHigherHeatingValue: 37.26,
      NodeGasStreamComponent: null,
      NodeFlowProfileNameByCategory: null,
      FlowCategoryList: null,
      GateStationPressureControlType: null,
      GateStationPressureSelect: null,
      GateStationPressureValue: null,
      GateStationFlowSelect: null,
      GateStationFlowValue: null,
    },
    {
      NodeName: '西海岸东方至尊',
      NodeType: 2,
      NodeStatus: 'Known Flow',
      NodeId: 4269,
      NodePressure: '297.03',
      NodeFlow: '458.519',
      NodeReferencePressure: '3519.00',
      NodeReferenceFlow: null,
      NodeXCoordinate: '112195.7',
      NodeYCoordinate: '37583.8',
      NodeResultPressure: '297.03',
      NodeResultFlow: '458.519',
      NodeDescription: null,
      NodeHigherHeatingValue: 37.26,
      NodeGasStreamComponent: null,
      NodeFlowProfileNameByCategory: null,
      FlowCategoryList: null,
      GateStationPressureControlType: null,
      GateStationPressureSelect: null,
      GateStationPressureValue: null,
      GateStationFlowSelect: null,
      GateStationFlowValue: null,
    },
    {
      NodeName: '东岳普天汽配',
      NodeType: 2,
      NodeStatus: 'Known Flow',
      NodeId: 4271,
      NodePressure: '283.59',
      NodeFlow: '458.519',
      NodeReferencePressure: '3519.00',
      NodeReferenceFlow: null,
      NodeXCoordinate: '112195.7',
      NodeYCoordinate: '37583.8',
      NodeResultPressure: '283.59',
      NodeResultFlow: '458.519',
      NodeDescription: null,
      NodeHigherHeatingValue: 37.26,
      NodeGasStreamComponent: null,
      NodeFlowProfileNameByCategory: null,
      FlowCategoryList: null,
      GateStationPressureControlType: null,
      GateStationPressureSelect: null,
      GateStationPressureValue: null,
      GateStationFlowSelect: null,
      GateStationFlowValue: null,
    },
    {
      NodeName: '水灵山路纸业锅炉',
      NodeType: 2,
      NodeStatus: 'Known Flow',
      NodeId: 4272,
      NodePressure: '313',
      NodeFlow: '458.519',
      NodeReferencePressure: '3519.00',
      NodeReferenceFlow: null,
      NodeXCoordinate: '112195.7',
      NodeYCoordinate: '37583.8',
      NodeResultPressure: '313',
      NodeResultFlow: '458.519',
      NodeDescription: null,
      NodeHigherHeatingValue: 37.26,
      NodeGasStreamComponent: null,
      NodeFlowProfileNameByCategory: null,
      FlowCategoryList: null,
      GateStationPressureControlType: null,
      GateStationPressureSelect: null,
      GateStationPressureValue: null,
      GateStationFlowSelect: null,
      GateStationFlowValue: null,
    },
    {
      NodeName: '七墩山路华燊',
      NodeType: 2,
      NodeStatus: 'Known Flow',
      NodeId: 4273,
      NodePressure: '247.88',
      NodeFlow: '458.519',
      NodeReferencePressure: '3519.00',
      NodeReferenceFlow: null,
      NodeXCoordinate: '112195.7',
      NodeYCoordinate: '37583.8',
      NodeResultPressure: '247.88',
      NodeResultFlow: '458.519',
      NodeDescription: null,
      NodeHigherHeatingValue: 37.26,
      NodeGasStreamComponent: null,
      NodeFlowProfileNameByCategory: null,
      FlowCategoryList: null,
      GateStationPressureControlType: null,
      GateStationPressureSelect: null,
      GateStationPressureValue: null,
      GateStationFlowSelect: null,
      GateStationFlowValue: null,
    },

    {
      NodeName: '盛海路聚大洋',
      NodeType: 2,
      NodeStatus: 'Known Flow',
      NodeId: 4274,
      NodePressure: '217.68',
      NodeFlow: '458.519',
      NodeReferencePressure: '3519.00',
      NodeReferenceFlow: null,
      NodeXCoordinate: '112195.7',
      NodeYCoordinate: '37583.8',
      NodeResultPressure: '217.68',
      NodeResultFlow: '458.519',
      NodeDescription: null,
      NodeHigherHeatingValue: 37.26,
      NodeGasStreamComponent: null,
      NodeFlowProfileNameByCategory: null,
      FlowCategoryList: null,
      GateStationPressureControlType: null,
      GateStationPressureSelect: null,
      GateStationPressureValue: null,
      GateStationFlowSelect: null,
      GateStationFlowValue: null,
    },

    {
      NodeName: '世纪大道卡地亚祥园',
      NodeType: 2,
      NodeStatus: 'Known Flow',
      NodeId: 4275,
      NodePressure: '219.64',
      NodeFlow: '458.519',
      NodeReferencePressure: '3519.00',
      NodeReferenceFlow: null,
      NodeXCoordinate: '112195.7',
      NodeYCoordinate: '37583.8',
      NodeResultPressure: '219.64',
      NodeResultFlow: '458.519',
      NodeDescription: null,
      NodeHigherHeatingValue: 37.26,
      NodeGasStreamComponent: null,
      NodeFlowProfileNameByCategory: null,
      FlowCategoryList: null,
      GateStationPressureControlType: null,
      GateStationPressureSelect: null,
      GateStationPressureValue: null,
      GateStationFlowSelect: null,
      GateStationFlowValue: null,
    },
  ],
  SGSolverDeviceValveList: [
    { ValveName: '阀门A', ValveStatus: true },
    { ValveName: '阀门B', ValveStatus: true },
    { ValveName: '阀门C', ValveStatus: false },
    { ValveName: '阀门D', ValveStatus: true },
    { ValveName: '阀门E', ValveStatus: true },
    { ValveName: '阀门F', ValveStatus: false },
    { ValveName: '阀门G', ValveStatus: false },
    { ValveName: '阀门H', ValveStatus: true },
    { ValveName: '阀门I', ValveStatus: true },
    { ValveName: '阀门J', ValveStatus: true },
  ],
  SGSolverDeviceRegulatorList: [
    {
      NodeName: '中油门站输中压',
      NodeType: 2,
      NodeStatus: 'Known Pressure',
      NodeId: 4001,
      NodePressure: '400.0',
      NodeFlow: '7095.00',
      NodeReferencePressure: null,
      NodeReferenceFlow: null,
      NodeXCoordinate: '149561.8',
      NodeYCoordinate: '38639.3',
      NodeResultPressure: '400.0',
      NodeResultFlow: '7095.00',
      NodeDescription: null,
      NodeHigherHeatingValue: 37.26,
      NodeGasStreamComponent: null,
      SGSolverProfileList: null,
      FlowCategoryList: null,
      GateStationPressureControlType: null,
      GateStationPressureSelect: null,
      GateStationPressureValue: null,
      GateStationFlowSelect: null,
      GateStationFlowValue: null,
    },
    {
      NodeName: '中油门站输次高压',
      NodeType: 2,
      NodeStatus: 'Known Pressure',
      NodeId: 4006,
      NodePressure: ' 1600.0',
      NodeFlow: '5077.00',
      NodeReferencePressure: null,
      NodeReferenceFlow: null,
      NodeXCoordinate: '149561.8',
      NodeYCoordinate: '38639.3',
      NodeResultPressure: '1600.0',
      NodeResultFlow: '5077.00',
      NodeDescription: null,
      NodeHigherHeatingValue: 37.26,
      NodeGasStreamComponent: null,
      SGSolverProfileList: null,
      FlowCategoryList: null,
      GateStationPressureControlType: null,
      GateStationPressureSelect: null,
      GateStationPressureValue: null,
      GateStationFlowSelect: null,
      GateStationFlowValue: null,
    },

    {
      NodeName: '藏马山调压器',
      NodeType: 2,
      NodeStatus: 'Known Pressure',
      NodeId: 4007,
      NodePressure: ' 1600.0',
      NodeFlow: '29224.00',
      NodeReferencePressure: null,
      NodeReferenceFlow: null,
      NodeXCoordinate: '149561.8',
      NodeYCoordinate: '38639.3',
      NodeResultPressure: '1600.0',
      NodeResultFlow: '29224.00',
      NodeDescription: null,
      NodeHigherHeatingValue: 37.26,
      NodeGasStreamComponent: null,
      SGSolverProfileList: null,
      FlowCategoryList: null,
      GateStationPressureControlType: null,
      GateStationPressureSelect: null,
      GateStationPressureValue: null,
      GateStationFlowSelect: null,
      GateStationFlowValue: null,
    },
    {
      NodeName: '铁山输中压',
      NodeType: 2,
      NodeStatus: 'Known Pressure',
      NodeId: 4012,
      NodePressure: ' 400.0',
      NodeFlow: '8038.00',
      NodeReferencePressure: null,
      NodeReferenceFlow: null,
      NodeXCoordinate: '149561.8',
      NodeYCoordinate: '38639.3',
      NodeResultPressure: '400.0',
      NodeResultFlow: '8038.00',
      NodeDescription: null,
      NodeHigherHeatingValue: 37.26,
      NodeGasStreamComponent: null,
      SGSolverProfileList: null,
      FlowCategoryList: null,
      GateStationPressureControlType: null,
      GateStationPressureSelect: null,
      GateStationPressureValue: null,
      GateStationFlowSelect: null,
      GateStationFlowValue: null,
    },
    {
      NodeName: '铁山输次高压',
      NodeType: 2,
      NodeStatus: 'Known Pressure',
      NodeId: 4013,
      NodePressure: ' 1600.0',
      NodeFlow: '12230.00',
      NodeReferencePressure: null,
      NodeReferenceFlow: null,
      NodeXCoordinate: '149561.8',
      NodeYCoordinate: '38639.3',
      NodeResultPressure: '1600.0',
      NodeResultFlow: '12230.00',
      NodeDescription: null,
      NodeHigherHeatingValue: 37.26,
      NodeGasStreamComponent: null,
      SGSolverProfileList: null,
      FlowCategoryList: null,
      GateStationPressureControlType: null,
      GateStationPressureSelect: null,
      GateStationPressureValue: null,
      GateStationFlowSelect: null,
      GateStationFlowValue: null,
    },
  ],

  SGSolverDeviceRegulatorExit: [
    {
      NodeName: '胶南临港门站',
      NodeType: 2,
      NodeStatus: 'Known Pressure',
      NodeId: 4014,
      NodePressure: ' 880.0',
      NodeFlow: '14000.000',
      NodeReferencePressure: null,
      NodeReferenceFlow: null,
      NodeXCoordinate: '149561.8',
      NodeYCoordinate: '38639.3',
      NodeResultPressure: '880.0',
      NodeResultFlow: '14000.00',
      NodeDescription: null,
      NodeHigherHeatingValue: 37.26,
      NodeGasStreamComponent: null,
      SGSolverProfileList: null,
      FlowCategoryList: null,
      GateStationPressureControlType: null,
      GateStationPressureSelect: null,
      GateStationPressureValue: null,
      GateStationFlowSelect: null,
      GateStationFlowValue: null,
    },
    {
      NodeName: '红石崖门站',
      NodeType: 2,
      NodeStatus: 'Known Pressure',
      NodeId: 4081,
      NodePressure: ' 972.25',
      NodeFlow: '10859.953',
      NodeReferencePressure: null,
      NodeReferenceFlow: null,
      NodeXCoordinate: '149561.8',
      NodeYCoordinate: '38639.3',
      NodeResultPressure: '972.25',
      NodeResultFlow: '10859.953',
      NodeDescription: null,
      NodeHigherHeatingValue: 37.26,
      NodeGasStreamComponent: null,
      SGSolverProfileList: null,
      FlowCategoryList: null,
      GateStationPressureControlType: null,
      GateStationPressureSelect: null,
      GateStationPressureValue: null,
      GateStationFlowSelect: null,
      GateStationFlowValue: null,
    },
    {
      RegulatorName: '团结路',
      RegulatorValue: 722.5,
      NodeFlow: '13593.84',
      NodeName: '铁山输次高压',
      NodeType: 2,
      NodeStatus: 'Known Pressure',
      NodeId: 4082,
      NodePressure: ' 1600.0',
      NodeFlow: '12230.00',
      NodeReferencePressure: null,
      NodeReferenceFlow: null,
      NodeXCoordinate: '149561.8',
      NodeYCoordinate: '38639.3',
      NodeResultPressure: '1600.0',
      NodeResultFlow: '12230.00',
      NodeDescription: null,
      NodeHigherHeatingValue: 37.26,
      NodeGasStreamComponent: null,
      SGSolverProfileList: null,
      FlowCategoryList: null,
      GateStationPressureControlType: null,
      GateStationPressureSelect: null,
      GateStationPressureValue: null,
      GateStationFlowSelect: null,
      GateStationFlowValue: null,
    },
    {
      NodeName: '王台无人值守站',
      NodeType: 2,
      NodeStatus: 'Known Pressure',
      NodeId: 4023,
      NodePressure: ' 638.50',
      NodeFlow: '2169.163',
      NodeReferencePressure: null,
      NodeReferenceFlow: null,
      NodeXCoordinate: '149561.8',
      NodeYCoordinate: '38639.3',
      NodeResultPressure: '638.5',
      NodeResultFlow: '2169.163',
      NodeDescription: null,
      NodeHigherHeatingValue: 37.26,
      NodeGasStreamComponent: null,
      SGSolverProfileList: null,
      FlowCategoryList: null,
      GateStationPressureControlType: null,
      GateStationPressureSelect: null,
      GateStationPressureValue: null,
      GateStationFlowSelect: null,
      GateStationFlowValue: null,
    },
    {
      NodeName: '黄山无人值守站',
      NodeType: 2,
      NodeStatus: 'Known Pressure',
      NodeId: 4024,
      NodePressure: ' 700.0',
      NodeFlow: '458.577',
      NodeReferencePressure: null,
      NodeReferenceFlow: null,
      NodeXCoordinate: '149561.8',
      NodeYCoordinate: '38639.3',
      NodeResultPressure: '700.0',
      NodeResultFlow: '458.577',
      NodeDescription: null,
      NodeHigherHeatingValue: 37.26,
      NodeGasStreamComponent: null,
      SGSolverProfileList: null,
      FlowCategoryList: null,
      GateStationPressureControlType: null,
      GateStationPressureSelect: null,
      GateStationPressureValue: null,
      GateStationFlowSelect: null,
      GateStationFlowValue: null,
    },
    {
      NodeName: '徐村无人值守站',
      NodeType: 2,
      NodeStatus: 'Known Pressure',
      NodeId: 4025,
      NodePressure: ' 750.0',
      NodeFlow: '4.01',
      NodeReferencePressure: null,
      NodeReferenceFlow: null,
      NodeXCoordinate: '149561.8',
      NodeYCoordinate: '38639.3',
      NodeResultPressure: '750.0',
      NodeResultFlow: '4.01',
      NodeDescription: null,
      NodeHigherHeatingValue: 37.26,
      NodeGasStreamComponent: null,
      SGSolverProfileList: null,
      FlowCategoryList: null,
      GateStationPressureControlType: null,
      GateStationPressureSelect: null,
      GateStationPressureValue: null,
      GateStationFlowSelect: null,
      GateStationFlowValue: null,
    },
    {
      NodeName: '灵山卫无人值守站',
      NodeType: 2,
      NodeStatus: 'Known Pressure',
      NodeId: 4026,
      NodePressure: ' 680.0',
      NodeFlow: '2669.632',
      NodeReferencePressure: null,
      NodeReferenceFlow: null,
      NodeXCoordinate: '149561.8',
      NodeYCoordinate: '38639.3',
      NodeResultPressure: '680.0',
      NodeResultFlow: '2669.632',
      NodeDescription: null,
      NodeHigherHeatingValue: 37.26,
      NodeGasStreamComponent: null,
      SGSolverProfileList: null,
      FlowCategoryList: null,
      GateStationPressureControlType: null,
      GateStationPressureSelect: null,
      GateStationPressureValue: null,
      GateStationFlowSelect: null,
      GateStationFlowValue: null,
    },
    {
      NodeName: '山前无人值守站',
      NodeType: 2,
      NodeStatus: 'Known Pressure',
      NodeId: 4027,
      NodePressure: ' 700.0',
      NodeFlow: '458.519',
      NodeReferencePressure: null,
      NodeReferenceFlow: null,
      NodeXCoordinate: '149561.8',
      NodeYCoordinate: '38639.3',
      NodeResultPressure: '700.0',
      NodeResultFlow: '458.519',
      NodeDescription: null,
      NodeHigherHeatingValue: 37.26,
      NodeGasStreamComponent: null,
      SGSolverProfileList: null,
      FlowCategoryList: null,
      GateStationPressureControlType: null,
      GateStationPressureSelect: null,
      GateStationPressureValue: null,
      GateStationFlowSelect: null,
      GateStationFlowValue: null,
    },
    {
      NodeName: '海尔大道无人值守站',
      NodeType: 2,
      NodeStatus: 'Known Pressure',
      NodeId: 4028,
      NodePressure: ' 550.0',
      NodeFlow: '2062.3',
      NodeReferencePressure: null,
      NodeReferenceFlow: null,
      NodeXCoordinate: '149561.8',
      NodeYCoordinate: '38639.3',
      NodeResultPressure: '550.0',
      NodeResultFlow: '2062.3',
      NodeDescription: null,
      NodeHigherHeatingValue: 37.26,
      NodeGasStreamComponent: null,
      SGSolverProfileList: null,
      FlowCategoryList: null,
      GateStationPressureControlType: null,
      GateStationPressureSelect: null,
      GateStationPressureValue: null,
      GateStationFlowSelect: null,
      GateStationFlowValue: null,
    },
    {
      NodeName: '西区铁山中压',
      NodeType: 2,
      NodeStatus: 'Known Pressure',
      NodeId: 4029,
      NodePressure: ' 1000.0',
      NodeFlow: '8083.00',
      NodeReferencePressure: null,
      NodeReferenceFlow: null,
      NodeXCoordinate: '149561.8',
      NodeYCoordinate: '38639.3',
      NodeResultPressure: '1000.0',
      NodeResultFlow: '8083.00',
      NodeDescription: null,
      NodeHigherHeatingValue: 37.26,
      NodeGasStreamComponent: null,
      SGSolverProfileList: null,
      FlowCategoryList: null,
      GateStationPressureControlType: null,
      GateStationPressureSelect: null,
      GateStationPressureValue: null,
      GateStationFlowSelect: null,
      GateStationFlowValue: null,
    },
    {
      NodeName: '金能用户',
      NodeType: 2,
      NodeStatus: 'Known Pressure',
      NodeId: 4030,
      NodePressure: ' 1000.0',
      NodeFlow: '6000.00',
      NodeReferencePressure: null,
      NodeReferenceFlow: null,
      NodeXCoordinate: '149561.8',
      NodeYCoordinate: '38639.3',
      NodeResultPressure: '1000.0',
      NodeResultFlow: '6000.00',
      NodeDescription: null,
      NodeHigherHeatingValue: 37.26,
      NodeGasStreamComponent: null,
      SGSolverProfileList: null,
      FlowCategoryList: null,
      GateStationPressureControlType: null,
      GateStationPressureSelect: null,
      GateStationPressureValue: null,
      GateStationFlowSelect: null,
      GateStationFlowValue: null,
    },
    {
      NodeName: '开城路站',
      NodeType: 2,
      NodeStatus: 'Known Pressure',
      NodeId: 4031,
      NodePressure: ' 1600.0',
      NodeFlow: '9200.00',
      NodeReferencePressure: null,
      NodeReferenceFlow: null,
      NodeXCoordinate: '149561.8',
      NodeYCoordinate: '38639.3',
      NodeResultPressure: '1600.0',
      NodeResultFlow: '9200.00',
      NodeDescription: null,
      NodeHigherHeatingValue: 37.26,
      NodeGasStreamComponent: null,
      SGSolverProfileList: null,
      FlowCategoryList: null,
      GateStationPressureControlType: null,
      GateStationPressureSelect: null,
      GateStationPressureValue: null,
      GateStationFlowSelect: null,
      GateStationFlowValue: null,
    },

    {
      NodeName: '张家楼',
      NodeType: 2,
      NodeStatus: 'Known Pressure',
      NodeId: 4032,
      NodePressure: ' 1200.0',
      NodeFlow: '600.00',
      NodeReferencePressure: null,
      NodeReferenceFlow: null,
      NodeXCoordinate: '149561.8',
      NodeYCoordinate: '38639.3',
      NodeResultPressure: '1200.0',
      NodeResultFlow: '600.00',
      NodeDescription: null,
      NodeHigherHeatingValue: 37.26,
      NodeGasStreamComponent: null,
      SGSolverProfileList: null,
      FlowCategoryList: null,
      GateStationPressureControlType: null,
      GateStationPressureSelect: null,
      GateStationPressureValue: null,
      GateStationFlowSelect: null,
      GateStationFlowValue: null,
    },
    {
      NodeName: '琅琊',
      NodeType: 2,
      NodeStatus: 'Known Pressure',
      NodeId: 4033,
      NodePressure: ' 1200.0',
      NodeFlow: '500.00',
      NodeReferencePressure: null,
      NodeReferenceFlow: null,
      NodeXCoordinate: '149561.8',
      NodeYCoordinate: '38639.3',
      NodeResultPressure: '1200.0',
      NodeResultFlow: '500.00',
      NodeDescription: null,
      NodeHigherHeatingValue: 37.26,
      NodeGasStreamComponent: null,
      SGSolverProfileList: null,
      FlowCategoryList: null,
      GateStationPressureControlType: null,
      GateStationPressureSelect: null,
      GateStationPressureValue: null,
      GateStationFlowSelect: null,
      GateStationFlowValue: null,
    },
    {
      NodeName: '藏马山',
      NodeType: 2,
      NodeStatus: 'Known Pressure',
      NodeId: 4034,
      NodePressure: ' 1505.0',
      NodeFlow: '334.00',
      NodeReferencePressure: null,
      NodeReferenceFlow: null,
      NodeXCoordinate: '149561.8',
      NodeYCoordinate: '38639.3',
      NodeResultPressure: '1505.0',
      NodeResultFlow: '334.00',
      NodeDescription: null,
      NodeHigherHeatingValue: 37.26,
      NodeGasStreamComponent: null,
      SGSolverProfileList: null,
      FlowCategoryList: null,
      GateStationPressureControlType: null,
      GateStationPressureSelect: null,
      GateStationPressureValue: null,
      GateStationFlowSelect: null,
      GateStationFlowValue: null,
    },
    {
      NodeName: '董家口',
      NodeType: 2,
      NodeStatus: 'Known Pressure',
      NodeId: 4035,
      NodePressure: ' 1000.0',
      NodeFlow: '1095.00',
      NodeReferencePressure: null,
      NodeReferenceFlow: null,
      NodeXCoordinate: '149561.8',
      NodeYCoordinate: '38639.3',
      NodeResultPressure: '1000.0',
      NodeResultFlow: '1095.00',
      NodeDescription: null,
      NodeHigherHeatingValue: 37.26,
      NodeGasStreamComponent: null,
      SGSolverProfileList: null,
      FlowCategoryList: null,
      GateStationPressureControlType: null,
      GateStationPressureSelect: null,
      GateStationPressureValue: null,
      GateStationFlowSelect: null,
      GateStationFlowValue: null,
    },
  ],
}

export const abnormalLeftData = {
  list: [
    { name: '管道1234', reason: '超速', num: '25m/s' },
    { name: '管道1235', reason: '超压损', num: '100kpa/km' },
    { name: '管道1236', reason: '超速', num: '25m/s' },
    { name: '管道1237', reason: '超速', num: '25m/s' },
  ],
}

export const abnormalRightData = {
  list: [
    { name: '珠山苑', pressure: '98', x: 514211.32, y: 3988339.05 },
    { name: '朱雀台', pressure: '102', x: 519552.28, y: 3980252.41 },
    { name: '中泽国货', pressure: '88', x: 512941.34, y: 3987697.7 },
    { name: '中煤花园', pressure: '112', x: 517029.69, y: 3980955.24 },
    { name: '中集', pressure: '97', x: 517664.11, y: 3989809.48 },
  ],
}

export const gisConduitData1 = [
  {
    id: 0,
    data: {
      conduit: [
        { name: '管道1234', flow: '654', flowSpeed: '5' },
        { name: '管道1333', flow: '445', flowSpeed: '7' },
        { name: '管道1244', flow: '445', flowSpeed: '7' },
        { name: '管道1245', flow: '445', flowSpeed: '7' },
      ],
      node: [
        { name: '用户1234', usegas: '654', pressure: '200' },
        { name: '用户1234', usegas: '654', pressure: '200' },
        { name: '用户1234', usegas: '654', pressure: '200' },
        { name: '用户1234', usegas: '654', pressure: '200' },
        { name: '用户1234', usegas: '654', pressure: '200' },
      ],
    },
  },
  {
    id: 1,
    data: {
      conduit: [
        { name: '管道2234', flow: '654', flowSpeed: '5' },
        { name: '管道2333', flow: '445', flowSpeed: '7' },
        { name: '管道2244', flow: '445', flowSpeed: '7' },
        { name: '管道2245', flow: '445', flowSpeed: '7' },
        { name: '管道2245', flow: '445', flowSpeed: '7' },
      ],
      node: [
        { name: '用户2234', usegas: '654', pressure: '200' },
        { name: '用户2234', usegas: '654', pressure: '200' },
        { name: '用户2234', usegas: '654', pressure: '200' },
        { name: '用户2234', usegas: '654', pressure: '200' },
        { name: '用户2234', usegas: '654', pressure: '200' },
        { name: '用户2234', usegas: '654', pressure: '200' },
        { name: '用户2234', usegas: '654', pressure: '200' },
        { name: '用户2234', usegas: '654', pressure: '200' },
      ],
    },
  },
  {
    id: 2,
    data: {
      conduit: [
        { name: '管道3234', flow: '654', flowSpeed: '5' },
        { name: '管道3333', flow: '445', flowSpeed: '7' },
        { name: '管道3244', flow: '445', flowSpeed: '7' },
        { name: '管道3245', flow: '445', flowSpeed: '7' },
      ],
      node: [
        { name: '用3234', usegas: '654', pressure: '200' },
        { name: '用3234', usegas: '654', pressure: '200' },
        { name: '用3234', usegas: '654', pressure: '200' },
        { name: '用3234', usegas: '654', pressure: '200' },
      ],
    },
  },
  {
    id: 3,
    children: [
      {
        id: 0,
        data: {
          conduit: [
            { name: '管道5234', flow: '654', flowSpeed: '5' },
            { name: '管道5333', flow: '445', flowSpeed: '7' },
            { name: '管道5244', flow: '445', flowSpeed: '7' },
            { name: '管道5245', flow: '445', flowSpeed: '7' },
            { name: '管道5245', flow: '445', flowSpeed: '7' },
          ],
          node: [
            { name: '用户5234', usegas: '654', pressure: '200' },
            { name: '用户5234', usegas: '654', pressure: '200' },
            { name: '用户5234', usegas: '654', pressure: '200' },
            { name: '用户5234', usegas: '654', pressure: '200' },
            { name: '用户5234', usegas: '654', pressure: '200' },
            { name: '用户5234', usegas: '654', pressure: '200' },
          ],
        },
      },
      {
        id: 1,
        data: {
          conduit: [
            { name: '管道6234', flow: '654', flowSpeed: '5' },
            { name: '管道6333', flow: '445', flowSpeed: '7' },
            { name: '管道6244', flow: '445', flowSpeed: '7' },
            { name: '管道6245', flow: '445', flowSpeed: '7' },
            { name: '管道6245', flow: '445', flowSpeed: '7' },
            { name: '管道6245', flow: '445', flowSpeed: '7' },
          ],
          node: [
            { name: '用户6234', usegas: '654', pressure: '200' },
            { name: '用户6234', usegas: '654', pressure: '200' },
            { name: '用户6234', usegas: '654', pressure: '200' },
            { name: '用户6234', usegas: '654', pressure: '200' },
            { name: '用户6234', usegas: '654', pressure: '200' },
            { name: '用户6234', usegas: '654', pressure: '200' },
          ],
        },
      },
      {
        id: 2,
        data: {
          conduit: [
            { name: '管道7234', flow: '654', flowSpeed: '5' },
            { name: '管道7333', flow: '445', flowSpeed: '7' },
            { name: '管道7244', flow: '445', flowSpeed: '7' },
            { name: '管道7245', flow: '445', flowSpeed: '7' },
          ],
          node: [
            { name: '用户7234', usegas: '654', pressure: '200' },
            { name: '用户7234', usegas: '654', pressure: '200' },
            { name: '用户7234', usegas: '654', pressure: '200' },
            { name: '用户7234', usegas: '654', pressure: '200' },
          ],
        },
      },
      {
        id: 3,
        data: {
          conduit: [
            { name: '管8234', flow: '654', flowSpeed: '5' },
            { name: '管8333', flow: '445', flowSpeed: '7' },
            { name: '管8244', flow: '445', flowSpeed: '7' },
          ],
          node: [
            { name: '用户8234', usegas: '654', pressure: '200' },
            { name: '用户8234', usegas: '654', pressure: '200' },
            { name: '用户8234', usegas: '654', pressure: '200' },
            { name: '用户8234', usegas: '654', pressure: '200' },
          ],
        },
      },
      {
        id: 4,
        data: {
          conduit: [
            { name: '管道9234', flow: '654', flowSpeed: '5' },
            { name: '管道9333', flow: '445', flowSpeed: '7' },
            { name: '管道9244', flow: '445', flowSpeed: '7' },
            { name: '管道9245', flow: '445', flowSpeed: '7' },
            { name: '管道9245', flow: '445', flowSpeed: '7' },
            { name: '管道9245', flow: '445', flowSpeed: '7' },
          ],
          node: [
            { name: '用户9234', usegas: '654', pressure: '200' },
            { name: '用户9234', usegas: '654', pressure: '200' },
            { name: '用户9234', usegas: '654', pressure: '200' },
            { name: '用户9234', usegas: '654', pressure: '200' },
            { name: '用户9234', usegas: '654', pressure: '200' },
            { name: '用户9234', usegas: '654', pressure: '200' },
            { name: '用户9234', usegas: '654', pressure: '200' },
            { name: '用户9234', usegas: '654', pressure: '200' },
          ],
        },
      },
      {
        id: 5,
        data: {
          conduit: [
            { name: '管道10234', flow: '654', flowSpeed: '5' },
            { name: '管道10333', flow: '445', flowSpeed: '7' },
            { name: '管道10244', flow: '445', flowSpeed: '7' },
            { name: '管道10245', flow: '445', flowSpeed: '7' },
          ],
          node: [
            { name: '用户10234', usegas: '654', pressure: '200' },
            { name: '用户10234', usegas: '654', pressure: '200' },
            { name: '用户10234', usegas: '654', pressure: '200' },
            { name: '用户10234', usegas: '654', pressure: '200' },
            { name: '用户10234', usegas: '654', pressure: '200' },
            { name: '用户10234', usegas: '654', pressure: '200' },
          ],
        },
      },
      {
        id: 6,
        data: {
          conduit: [
            { name: '管道11234', flow: '654', flowSpeed: '5' },
            { name: '管道11333', flow: '445', flowSpeed: '7' },
            { name: '管道11244', flow: '445', flowSpeed: '7' },
            { name: '管道11245', flow: '445', flowSpeed: '7' },
          ],
          node: [
            { name: '用户11234', usegas: '654', pressure: '200' },
            { name: '用户11234', usegas: '654', pressure: '200' },
            { name: '用户11234', usegas: '654', pressure: '200' },
            { name: '用户11234', usegas: '654', pressure: '200' },
            { name: '用户11234', usegas: '654', pressure: '200' },
            { name: '用户11234', usegas: '654', pressure: '200' },
          ],
        },
      },
      {
        id: 7,
        data: {
          conduit: [
            { name: '管道12234', flow: '654', flowSpeed: '5' },
            { name: '管道12333', flow: '445', flowSpeed: '7' },
            { name: '管道12244', flow: '445', flowSpeed: '7' },
            { name: '管道12245', flow: '445', flowSpeed: '7' },
            { name: '管道12245', flow: '445', flowSpeed: '7' },
          ],
          node: [
            { name: '用户12234', usegas: '654', pressure: '200' },
            { name: '用户12234', usegas: '654', pressure: '200' },
            { name: '用户12234', usegas: '654', pressure: '200' },
            { name: '用户12234', usegas: '654', pressure: '200' },
            { name: '用户12234', usegas: '654', pressure: '200' },
            { name: '用户12234', usegas: '654', pressure: '200' },
            { name: '用户12234', usegas: '654', pressure: '200' },
          ],
        },
      },
      {
        id: 8,
        data: {
          conduit: [
            { name: '管道13234', flow: '654', flowSpeed: '5' },
            { name: '管道13333', flow: '445', flowSpeed: '7' },
            { name: '管道13244', flow: '445', flowSpeed: '7' },
            { name: '管道13245', flow: '445', flowSpeed: '7' },
          ],
          node: [
            { name: '用户13234', usegas: '654', pressure: '200' },
            { name: '用户13234', usegas: '654', pressure: '200' },
            { name: '用户13234', usegas: '654', pressure: '200' },
            { name: '用户13234', usegas: '654', pressure: '200' },
          ],
        },
      },
    ],
  },
]

export const gisConduitData2 = [
  {
    id: 0,
    data: {
      conduit: [
        { name: '管道10234', flow: '654', flowSpeed: '5' },
        { name: '管道10333', flow: '445', flowSpeed: '7' },
        { name: '管道10244', flow: '445', flowSpeed: '7' },
        { name: '管道10245', flow: '445', flowSpeed: '7' },
        { name: '管道10245', flow: '445', flowSpeed: '7' },
      ],
      node: [
        { name: '用户10234', usegas: '654', pressure: '200' },
        { name: '用户10234', usegas: '654', pressure: '200' },
        { name: '用户10234', usegas: '654', pressure: '200' },
        { name: '用户10234', usegas: '654', pressure: '200' },
        { name: '用户10234', usegas: '654', pressure: '200' },
        { name: '用户10234', usegas: '654', pressure: '200' },
        { name: '用户10234', usegas: '654', pressure: '200' },
      ],
    },
  },
]

export const gisConduitData3 = [
  {
    id: 0,
    data: {
      conduit: [
        { name: '管道111234', flow: '654', flowSpeed: '5' },
        { name: '管道111333', flow: '445', flowSpeed: '7' },
        { name: '管道111244', flow: '445', flowSpeed: '7' },
        { name: '管道111245', flow: '445', flowSpeed: '7' },
      ],
      node: [
        { name: '用户111234', usegas: '654', pressure: '200' },
        { name: '用户111234', usegas: '654', pressure: '200' },
        { name: '用户111234', usegas: '654', pressure: '200' },
        { name: '用户111234', usegas: '654', pressure: '200' },
        { name: '用户111234', usegas: '654', pressure: '200' },
      ],
    },
  },
]
